POST http://localhost:9999/v1/Session/logout HTTP/1.1
content-type: application/json
Cookie: IdentityToken=eyJhbGciOiJIUzI1NiIsImtpZCI6IjVmMDFlOTE0LWY5MTktNDljNS05MjFiLWYzMDMwNWE3MDBlZCIsInRva2VuIjoiSWRlbnRpdHlUb2tlbiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrYW5qaWt1X2JhY2tlbmQiLCJpYXQiOjE3MzgxNzk1MDMuOTI2MjQ2LCJuYmYiOjE3MzgxNzk1MDMuOTI2MjQ5LCJleHAiOjE3MzgxODMxMDMuOTI0MzY4LCJ1c2VyIjp7InVpZCI6IjQ3OGRmZWY2LWYyNGQtNDEwYS1iZDIxLTI3ODUwMTdmMWIyOCIsInVzZXJuYW1lIjoidGVzdC11c2VyIiwiZ3JvdXBzIjpbXSwicGVybWlzc2lvbnMiOnsiYWRtaW4iOmZhbHNlLCJlYXJseV9hY2Nlc3MiOmZhbHNlLCJtYW5hZ2VfcHJvamVjdHMiOmZhbHNlLCJ1cGxvYWRfY2hhcHRlcnMiOmZhbHNlLCJtb2RlcmF0ZV9hdmF0YXJzIjpmYWxzZSwidmlld19oaWRkZW4iOmZhbHNlfX19.E1bo7NfbKHmFP1hr5U1u3fH68oBMSMG-UfoJHW8j9kg; Path=/; Max-Age=3600; SameSite=Lax; Secure; HttpOnly
Cookie: RefreshToken=eyJhbGciOiJIUzI1NiIsImtpZCI6ImIyYjkyNzM2LWI3NDItNDNlOC05NzlhLWM2YzdhNmVkOWQxMSIsInRva2VuIjoiUmVmcmVzaFRva2VuIiwidHlwIjoiSldUIn0.eyJpc3MiOiJrYW5qaWt1X2JhY2tlbmQiLCJpYXQiOjE3MzgxNzk1MDMuOTI3MSwibmJmIjoxNzM4MTc5NTAzLjkyNzEwMiwiZXhwIjoxNzM4MjY1OTAzLjkyNjM0OCwiaWRfdG9rZW4iOiI1ZjAxZTkxNC1mOTE5LTQ5YzUtOTIxYi1mMzAzMDVhNzAwZWQifQ.wSDuB6bFLej6UbCRcMeTJyOivaeux8J45VKuRm2mVt8; Path=/; Max-Age=86400; SameSite=Lax; Secure; HttpOnly

{