GET http://localhost:9999/v1/Session/refresh HTTP/1.1
content-type: application/json
Cookie: IdentityToken=eyJhbGciOiJIUzI1NiIsImtpZCI6IjRjNjIxM2FmLTFkZDAtNDZjOS1hMmZiLTc5ODEzMGY0MTg4NCIsInRva2VuIjoiSWRlbnRpdHlUb2tlbiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrYW5qaWt1X2JhY2tlbmQiLCJpYXQiOjE3MzgxNzkxOTIuNzg3Mjg5LCJuYmYiOjE3MzgxNzkxOTIuNzg3MjkxLCJleHAiOjE3MzgxODI3OTIuNzg1NDk2LCJ1c2VyIjp7InVpZCI6ImU4MDEyMzUwLTg3YjktNDQwYy1iZjQ0LTU5OTRjODY5ODg3NyIsInVzZXJuYW1lIjoidGVzdC11c2VyIiwiZ3JvdXBzIjpbXSwicGVybWlzc2lvbnMiOnsiYWRtaW4iOmZhbHNlLCJlYXJseV9hY2Nlc3MiOmZhbHNlLCJtYW5hZ2VfcHJvamVjdHMiOmZhbHNlLCJ1cGxvYWRfY2hhcHRlcnMiOmZhbHNlLCJtb2RlcmF0ZV9hdmF0YXJzIjpmYWxzZSwidmlld19oaWRkZW4iOmZhbHNlfX19.GNO8HS_w3LnyMrLlUjhRlfi7rrs9gU7GuDB-V4wB2YY; Path=/; Max-Age=3600; SameSite=Lax; Secure; HttpOnly
Cookie: RefreshToken=eyJhbGciOiJIUzI1NiIsImtpZCI6ImM3ZDhjZDMwLTZiOTEtNDgxNS04NTkzLWNkZTM1ZDBjMjFmNSIsInRva2VuIjoiUmVmcmVzaFRva2VuIiwidHlwIjoiSldUIn0.eyJpc3MiOiJrYW5qaWt1X2JhY2tlbmQiLCJpYXQiOjE3MzgxNzkxOTIuNzg4MDYzLCJuYmYiOjE3MzgxNzkxOTIuNzg4MDY1LCJleHAiOjE3MzgyNjU1OTIuNzg3Mzg5LCJpZF90b2tlbiI6IjRjNjIxM2FmLTFkZDAtNDZjOS1hMmZiLTc5ODEzMGY0MTg4NCJ9.o2WmL2w2FrmusupEkC0vk01MFe5sY-kIzsjR0o8ZE18; Path=/; Max-Age=86400; SameSite=Lax; Secure; HttpOnly
