POST http://localhost:9999/v1/Session/refresh HTTP/1.1
content-type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsImtpZCI6IjAyOTA2Y2Q0LWFkZjAtNGE4OS05NDVmLTI5N2JhOTVhNmM5ZiIsInRva2VuIjoiSWRlbnRpdHlUb2tlbiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrYW5qaWt1X2JhY2tlbmQiLCJpYXQiOjE3MzgwMTA2ODEuNjE0NzY4LCJuYmYiOjE3MzkwMTA2ODEuNjE0NzcsImV4cCI6MTczODAxNDI4MS42MTI5NCwidXNlciI6eyJ1aWQiOiJkNDNkNWExZi1mYjkyLTRkMmQtYWYzYy03MTg4ZWJkMDMxMzEiLCJ1c2VybmFtZSI6InRlc3QtdXNlciIsImdyb3VwcyI6W10sInBlcm1pc3Npb25zIjp7ImFkbWluIjpmYWxzZSwiZWFybHlfYWNjZXNzIjpmYWxzZSwibWFuYWdlX3Byb2plY3RzIjpmYWxzZSwidXBsb2FkX2NoYXB0ZXJzIjpmYWxzZSwibW9kZXJhdGVfYXZhdGFycyI6ZmFsc2UsInZpZXdfaGlkZGVuIjpmYWxzZX19fQ.bkqq07g9ryCDfdiX6ycd3XtkUc3XbJtdMRpwLTeygzU"
}