cors_origin = "https://localhost:5173"
app_name = "img_upload_backend"
debug = true
port = 9999
listening_ip = "127.0.0.1"
db_url = "sqlite://test.db"

[Files]
image_path = "./images"
supported_image_types = ["jpeg", "png", "gif", "webp"]

[JWT]
issuer = "kanjiku_backend"
algorithm = "HS256"
secret = "supersecretjwtcode"


[[users]]
username = "admin2"
password = "admin"
email = "test@example.com"
groups = ["admin"]

[[users]]
username = "test123"
password = "test123"
email = "test2@example.com"

[[groups]]
name = "admin"
admin = true
view_hidden = true
early_access = true
manage_projects = true
upload_chapters = true
moderate_avatars = true
